### ISSUE TITLE
Should I change App key for my Android app when I switch from API v.1 to API v.2?

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#125]
My Android app uses API v.1. Now I'm going to switch to API v.2. Should I create new app in dropbox developer console and get a new api key for this? How to use old api key and do not to get message like on the [attached picture](https://user-images.githubusercontent.com/4918293/27915320-28e6afb0-6290-11e7-9df9-ee9ac0aefbe1.png), if I shouldn't?

**Comment by greg-db** [comment]
[Cross-linking for reference: https://www.dropboxforum.com/t5/API-support/Should-I-change-App-key-for-my-Android-app-when-I-switch-from/m-p/230933#M12569 ]

No, you do not need to register a new app key to use API v2. (One exception to that would be if your app is registered for the "file type" permission, which isn't supported by API v2.)

In order to dismiss that message, you need to log in to the account that owns that app, and go to the [App Console](https://www.dropbox.com/developers/apps). There will be a form there where you can "acknowledge" the API v1 deprecation. Once you do so, that message will no longer be displayed.

**Comment by isabsent** [comment]
What if I did not acknowledge v.1 deprecation, but have changed a code of my application in consistence with v.2 because I do not remember credentials of this Dropbox account? Will my app work after v.1 deprecation?

**Comment by greg-db** [comment]
Note that API v1 is already [deprecated](https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/). API v1 is going to be disabled later this year. Any further API v1 calls made once API v1 is disabled will fail. 

If your app is updated to use API v2, it will continue working once API v1 is disabled.
