### ISSUE TITLE
LastModified for folders?

### ISSUE THREAD

**Issue by isabsent** [dropbox/dropbox-sdk-java#130]
Is there a way to get last modified time for folder avoiding checking all files in the folder for last modified time?

**Comment by cakoose** [comment]
There is no way to get the last modified time for a folder.

But what is your high-level goal?  There may be other ways of achieving it.

For example, [listFolderContinue]](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue-java.lang.String-) can tell you what has changed in a folder since the last time you called the function.

**Comment by isabsent** [comment]
The target is to show a string with a last modified time under each folder on the screen for users of our file manager. Would yoube so kind to give a code example with using of listFolderContinue?

**Comment by cakoose** [comment]
Two more questions:
- (I'm assuming some kind of standard file manager view.)  Do you want to show the modified time of the folder they're currently viewing the contents of?  Or do you want to show the modified times for each folder in the current view?
- Do you want to show the last modification time of the folder's immediate children (shallow), or do you want to show the last modification time of all the folder's descendants (deep)?

If it's just the folder they're currently browsing and just shallow-modified times, loop through the folder contents and pick the last `clientModified` time.

If you want to shallow-modified times for each folders in the current view, that's trickier.  One option is to list those folders and pick the last modification time.  This is a lot of extra work, so you should probably cache things.

If you need deep-modified times, that's more work.  One way is to maintain a local cache of the full folder metadata tree (just metadata, not file contents) and compute the deep-modified time yourself locally.

To download the full folder metadata tree efficiently, call `listFolder`+`listFolderContinue` with `recursive=true`.  You can then keep your folder listing updated by calling `listFolderContinue` periodically.  This requires more storage on your end, and has a higher initial startup cost.

**Comment by isabsent** [comment]
I want to show the modified times for each sub-folder in the current view. Why don't you expose `modifiedTime` for each entry in the result of `listFolder` as it is in Google Drive, One Drive or Box for example. Why developers should do a lot of work for such a simple operation!?

**Comment by cakoose** [comment]
What specifically do you mean by "modified time" with respect to a folder?  Do you mean shallow-modified, deep-modified, or something else?

The Dropbox API v1 "modified" field was misleading.  It was usually the timestamp when the folder was created on the server or the time it was shared/unshared.  The lack of clarity around the meaning was the reason the field was dropped in API v2.

[Please note: I do not work for Dropbox anymore.  Just trying to help.]

**Comment by isabsent** [comment]
Thanks for your help! I would like to have a time of last modified file in the folder (in "deep" sense) as a time of folder last modified. Is it possible to force Dropbox team to add this feature to Dropbox API V2?

**Comment by greg-db** [comment]
Thanks for the feedback @isabsent , and thanks for helping @cakoose!

I can't promise if/when this might be implemented, but I've sent this along as a feature request to the team.

**Comment by cakoose** [comment]
BTW, providing deep-modified times is rare.

There are different cases where folder modification times could be updated:
1. When you add/remove an immediate child file/folder.
2. When any immediate child file gets modified.
3. When any descendant file/folder gets modified.

It looks like you want all three.  Most operating systems only provide #1.  The last time I checked, Google Drive didn't do any of them -- a folder's `modifiedTime` is basically just the creation time.  Not sure what One Drive and Box do.

**Comment by isabsent** [comment]
Thanks for clarification!

**Comment by outsidecoder** [comment]
Thought it might be useful to cross reference these two posts as I think in Europe this is a legal requirement otherwise Dropbox or business users of dropbox could be fined into the millions:-
https://www.dropboxforum.com/t5/API-support/Automatically-Deleting-Files-After-X-Days-General-Data/m-p/270733/highlight/true#M15997

**Comment by greg-db** [comment]
@outsidecoder Thanks! I'll follow up on your forum thread.

**Comment by surjikal** [comment]
This would be a very useful feature for me as well. I would like to get a list of all the directories / files modified between a given time range. Right now, I have to iterate over the entire directory tree every time I have to find new files. This takes a long time because my directory tree is very large.

**Comment by cakoose** [comment]
@surjikal: If you goal is to see all modifications that happen to files and folders in Dropbox, you can use `files/list_folder` and `files/list_folder/continue`.

They both return a `cursor` value.  The next time you want to check if anything changed, call `files/list_folder/continue` with your previous `cursor`.  You'll get back a list of everything that has changed since then.

If you want to get a list of all modifications for some time range that ends in the past, you can't do that directly with the Dropbox API.  But you could maintain a client-side copy of the Dropbox account's full metadata (with `files/list_folder/continue`) and query that copy.
