### ISSUE TITLE
Android core-sdk:0-snapshot not working 

### ISSUE THREAD

**Issue by suresh5535** [dropbox/dropbox-sdk-java#163]
i tried to run the app with above version and the android studio said 
"failed to resolve : com.dropbox.core:dropbox-core-sdk:0-SNAPSHOT"

I have Android studio 2.1.2 with gradle 2.10

**Comment by greg-db** [comment]
The "0-SNAPSHOT" version is for building the SDK from source. In that case, did you successfully build the SDK, per the instructions under [Building from source](https://github.com/dropbox/dropbox-sdk-java#building-from-source)?

Unless you need to change the source, it's generally better and easier to just install from a package manager repository though. There are instructions for doing so using Maven or Gradle in the [Setup instructions](https://github.com/dropbox/dropbox-sdk-java#setup). (I.e., you'd specify a version like "3.0.5" instead of "0-SNAPSHOT".)

**Comment by suresh5535** [comment]
Hey Greg , thanks for the reply.
i got it working when i tried with 3.0.5., but i noticed 3.0.6 in one of the files, not sure.
