### ISSUE TITLE
Failed to resolve: com.dropbox.core:dropbox-core-sdk:0-SNAPSHOT

### ISSUE THREAD

**Issue by narendra88** [dropbox/dropbox-sdk-java#172]
I have tried to work with examples/android in order to work with API-v2, but still facing the issue. I am getting error as - 

> Failed to resolve: com.dropbox.core:dropbox-core-sdk:0-SNAPSHOT

Please provide any solution for this.

**Comment by greg-db** [comment]
The "0-SNAPSHOT" version is for building the SDK from source. In that case, did you successfully build the SDK, per the instructions under [Building from source](https://github.com/dropbox/dropbox-sdk-java#building-from-source)?

Unless you need to change the source, it's generally better and easier to just install from a package manager repository though. There are instructions for doing so using Maven or Gradle in the [Setup instructions](https://github.com/dropbox/dropbox-sdk-java#setup). (I.e., you'd specify a version like "3.0.5" instead of "0-SNAPSHOT".)

**Comment by narendra88** [comment]
I have changed the lib to 3.0.5. But, its still giving same error. with the code -
  ```
//put the file to dropbox
  response = mDBApi.putFile("$email/$parent_directory_name/$thumbnail_img_name", inputStream,
                                file.length(), null, null)
```

It seems I need to change the code too, for uploading and picking up the file on/ from dropbox.
Is it so?

**Comment by greg-db** [comment]
That `mDBApi.putFile` code is for the old SDK, for accessing the now retired API v1. 

To use this current version of the SDK for API v2, you'll need to update your code to use the latest version of the interface, e.g., as documented:

https://github.com/dropbox/dropbox-sdk-java#try-some-api-requests

If that's not working for you, please share your latest config/code/error output.

**Comment by narendra88** [comment]
Thanks buddy, it worked :)
