### ISSUE TITLE
unable to get metadata for root folder

### ISSUE THREAD

**Issue by prashantharshi** [dropbox/dropbox-sdk-java#211]
i need metadata for root folder , so i did client.files().getMetadata("/") but it gave me error showing root folder is disallowed. i need its folder id in format id:-Mdede... just like other folder id's

**Comment by greg-db** [comment]
This is the expected behavior; the root folder doesn't have metadata and so you can't call `getMetadata` for it.

If you want to list the contents of the root folder, you should use [`listFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder-java.lang.String-) (or [`listFolderBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderBuilder-java.lang.String-)), and supply the empty string `""` as the path, and [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue-java.lang.String-), as necessary.
