### ISSUE TITLE
How check that the access token has expired?

### ISSUE THREAD

**Issue by sergeymild** [dropbox/dropbox-sdk-java#262]
When i get access token and save it to SharedPrefereces. How check that this access token has expired?

**Comment by greg-db** [comment]
To check the validity of an access token, you'll need to make an API call with it and check the result. For instance, [the `getCurrentAccount` method](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/users/DbxUserUsersRequests.html#getCurrentAccount--) is a good one to use since it doesn't have any side effects. If the access token isn't valid, the call will throw [an `InvalidAccessTokenException`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/InvalidAccessTokenException.html).
