### ISSUE TITLE
Unable to enforce Business AccountType login

### ISSUE THREAD

**Issue by vabhatia** [dropbox/dropbox-sdk-java#277]
I have integrated Dropbox SDK into my Android app and have an enterprise related scenario where only business accounts types should be allowed to login. Does Dropbox SDK permit this?

I can detect the AccountType info after the user has logged in and can sign him out if he is not a business account user but it would be great if this can be enforced during the sign in only.

**Comment by greg-db** [comment]
[ Cross-linking for reference: [https://stackoverflow.com/questions/61774711/how-do-i-enforce-users-to-only-sign-in-with-their-business-accounts-in-dropbox-s](https://stackoverflow.com/questions/61774711/how-do-i-enforce-users-to-only-sign-in-with-their-business-accounts-in-dropbox-s) ]

The Android app authorization flow built in to the SDK doesn't offer a way to enforce this, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though. 

For reference, this is available in the Dropbox OAuth app authorization flow itself via [the `require_role` parameter on /oauth2/authorize](https://www.dropbox.com/developers/documentation/http/documentation#oauth2-authorize). That's [exposed in `DbxWebAuth`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/DbxWebAuth.Request.Builder.html#withRequireRole-java.lang.String-), but unfortunately isn't implemented in the Android flow (e.g., when using [`startOAuth2Authentication`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/android/Auth.html#startOAuth2Authentication-android.content.Context-java.lang.String-java.lang.String-java.lang.String:A-java.lang.String-java.lang.String-)).

**Comment by handstandsam** [comment]
@greg-db What should we do with this ticket?  It's been inactive for 2 years.

**Comment by greg-db** [comment]
@handstandsam It's still a valid feature request, but if there are no plans to implement it, you can close the issue as such.

**Comment by handstandsam** [comment]
Thanks.  There are no plans for this currently from the Android side of things.

**If** changes were to be done it would require coordination with multiple teams and surfaces.
* Dropbox Android app update to accept native auth requests with an option to only allow work accounts.  I'm not sure how easy it would be to query the dropbox app to check and see if that type of account was available, and ensure that a user is logging in with only a work account.
* Dropbox web auth requests would also need this capability, and we'd have to coordinate with that with multiple teams to update flows, UI and messaging.
---
Because of the complexity of this, I'm going to close unless there is a greater effort to add general support for this sort of flow.
