### ISSUE TITLE
ListFolder gets one file for call

### ISSUE THREAD

**Issue by riemann89** [dropbox/dropbox-sdk-java#284]
I have implemented a mechanism to list all files from a given Dropbox folder by using `ListFolder` and `ListFolderContinue`. My folder has roughly 90k files, after I get 60k unfortunately `result.getEntries` returns just on file at the time. Note that the code have been working well for a while.

Any explanation for this behaviour? Thanks

**Comment by greg-db** [comment]
Due to various factors, the exact number of entries you may get back per `listFolder`/`listFolderContinue` page can vary, and so cannot be guaranteed to be consistent over time, or across accounts or different folders, etc.

For example, in the particular account you're using, it sounds like there is a large amount of files and a long history of file changes, so listing through the files may take a significant number of calls. Exactly how many calls it will take can't be estimated ahead of time though and can change, e.g., as factors on the server-side change. (I'll pass this along as feedback to the team to see if the performance can be improved, but I can't make any promises unfortunately.)

**Comment by samthebest** [comment]
@greg-db  If there is a 25k limit on number of calls to the dropbox API (per month), and you return 1 file in a listing per call, how are we supposed to list a folder more than 25k files?  Should we be requesting an increase on that limit (and wait 8 hours!)?

The problem here is not inconsistency in the number of files, in fact its behaving consistently ... it's consistently giving only a single file (after some point).

All we are trying to do here is list 1 folder about once a day, which doesn't have insane number of files in it for 2020.  If your API cannot do that, I cannot see how you feel justified in closing this.  You might as well not provide an API and save your customers the hassel of writing code to hit it just to find out that it "cannot be guaranteed [to actually be useful]".

We are going to have to escalate our side through our enterprise channels.

**Comment by greg-db** [comment]
@samthebest Please note that the "25k limit" you're referring to is a limit on the number of "data transport" calls and does not apply to these `listFolder`/`listFolderContinue` calls anyway, so you don't need to worry about that limit with regards to this. (For reference, [that monthly "data transport" limit](https://www.dropbox.com/plans?trigger=nr) only applies to upload calls in particular, and only for certain Business plans. Also, it's also been increased to 1 million per team per month.)

None the less, thanks for the feedback! I'll pass this along as well.
