### ISSUE TITLE
BadRequestException occurs in DownloadBuilder.start only on Android 4.4 and 5.0

### ISSUE THREAD

**Issue by graynote** [dropbox/dropbox-sdk-java#287]
When DownloadBuilder.start() is called, BadRequestException (response code 400, no message) always occurs on Android version 4.4 and 5.0.  I recently heard the download issue from the user. I am not sure when this problem started.

```
DownloadBuilder builder = dbxClientV2.files().downloadBuilder(path);
InputStream is = builder.start().getInputStream();
```

DbxUserFilesRequests.download also has the same issue

`dbxClientV2.files().download(path);`

**Comment by greg-db** [comment]
Thanks for the report. Can you let me know which version number of the Dropbox Java SDK you're using?

**Comment by graynote** [comment]
I have tested it using 3.1.4, 3.0.11, 3.0.8. All of them have the same issue.

**Comment by greg-db** [comment]
Thanks. Just to be clear though, are you saying the issue does reproduce for you in the Android 5.0 emulator with the Dropbox SDK v3.1.4? (You just say you tested it there, but I want to make sure that means it also reproduces on emulator for you.) I ask because I just tried Dropbox SDK v3.1.4 in an Android 5.0.2 emulator and the issue doesn't reproduce for me, using either of the above pieces of code. 

Can you double check that the installation for v3.1.4 in particular succeeded and that you then can reproduce the issue with that? There was an issue like this but it only affected v3.0.11 and below, and shouldn't affect v3.1.4.

Otherwise, can you also share the code for how you're building your client and request config? That may be relevant. (Please don't include any access token though.)

**Comment by graynote** [comment]
You are right. 3.1.4 does not have the problem. I think I made a mistake when testing multiple versions. I will update the library to the latest 3.1.4 version.
