### ISSUE TITLE
Is there any way to get list of changes since some timestamp ?

### ISSUE THREAD

**Issue by slavag** [dropbox/dropbox-sdk-java#292]
Hi,
I'm looking for a way to get list of changes since some timestamp ?
From the API / SDK I see there's only way is to iterate over folder(s) starting from the root and checking on each file / folder modified time, but on large accounts this can be very long process.
Is this something that returns list of changes / changes feed ?

Thanks

**Comment by greg-db** [comment]
No, the Dropbox API doesn't offer a way to list/filter files only since a specific date, but I'll pass this along as a feature request. I can't promise if or when that might be implemented though. 

Instead, you'll need to list items using the [`listFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder-java.lang.String-)/[`listFolderBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderBuilder-java.lang.String-)/[`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue-java.lang.String-) methods via [the process and pagination detailed in the documentation](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder-java.lang.String-), iterate over the entries, and filter to the dates you want like you said. Once you do that though, you can stay up to date with just new changes by storing the last cursor you received, and then continuing to call [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderContinue-java.lang.String-) as necessary; that will return just new changes since you last called.

**Comment by slavag** [comment]
Thanks, ia thia cursor is long living (days)? Is it can be cursor for root folder and will provide to all hierarchy recursive? Or each folder and sub folder has it's own cursor?
Thanks

**Comment by greg-db** [comment]
Yes, these cursors are long-lived, and can be used over spans of days. They can become invalid in some cases though, so make sure you write your code to be able to handle [`ListFolderContinueError.RESET`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/ListFolderContinueError.html#RESET).

And yes, if you specify an initial path of `""`, that will return results for the root folder. And you can use [`ListFolderBuilder.withRecursive`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/ListFolderBuilder.html#withRecursive-java.lang.Boolean-) if you want recursive results.

The cursor will apply to whatever parameters you used initially (essentially each cursor "remembers" the initial settings from [`listFolder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolder-java.lang.String-)/[`listFolderBuilder`](https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#listFolderBuilder-java.lang.String-) used to get it).

**Comment by slavag** [comment]
Great, thanks.
