### ISSUE TITLE
Cannot authenticate on Android after SDK update

### ISSUE THREAD

**Issue by PhilippC** [dropbox/dropbox-sdk-java#319]
I have updated the SDK version used by my Android App (`com.dropbox.core:dropbox-core-sdk` from 3.1.1 to 4.0.0) and changed my implementation so it is compatible with short-lived access tokens using the DbxCredential class.

When trying to authenticate, I see the Dropbox App pop up asking if I want to grant access for my app. When I click the Accept button (or Grant button, in German it's "Zulassen"), I get "We couldn't connect to Dropbox. Please check your internet connection and try again" (translated from German). However, my internet connection is fine, and after switching back to the previous implementation works fine.

I entered my app-key in the Android example of the SDK and get the same behavior.

Is there anything I need to change to the auth settings of my app? I changed the Access token expiration to Short-lived.

**Comment by greg-db** [comment]
Are you using an app key for an app that hasn't been migrated to scopes yet? This can occur if so. (Apologies for the unhelpful error message!) In order to use the updated app authorization flow, you'll need to use an app key for an app that is set to use scopes.

You can migrate an existing app to scopes via the app's page on [the App Console](https://www.dropbox.com/developers/apps).

**Comment by PhilippC** [comment]
thanks for the response. That actually solved my issue! I agree that the error message could be more useful, though.
