### ISSUE TITLE
Android Api 30 package visibility changes

### ISSUE THREAD

**Issue by iyosifov** [dropbox/dropbox-sdk-java#321]
The SDK seems to specially integrate with the android dropbox app and checks whether it's installed.
For this to work in apps targeting api 30 you need in the manifest:

    <queries>
        <package android:name="com.dropbox.android" />
    </queries>

Ideally, your sdk should come with a library manifest, that will be merged into the containing app. 

https://developer.android.com/training/package-visibility

**Comment by greg-db** [comment]
Thanks for sharing this! I'll ask the team to incorporate this.

**Comment by AfzalivE** [comment]
@iyosifov Would this issue be the same as this problem?

![image](https://user-images.githubusercontent.com/436057/125178312-aa722380-e1b1-11eb-87ee-7fd4820bbdb0.png)

**Comment by iyosifov** [comment]
Probably, if your app is targeting api 30 and you're testing on api 30.

**Comment by greg-db** [comment]
@AfzalivE While that may be caused by the same visibility changes mentioned here, it looks like you're actually using [the deprecated Dropbox Chooser for Android](https://www.dropbox.com/developers/chooser#android) (which is different than [the Dropbox Java SDK](https://github.com/dropbox/dropbox-sdk-java) being discussed here). You may be able to address that issue the same way as indicated here, but we recommend migrating off of that anyway.

**Comment by wclausen** [comment]
We have updated the documentation in the README to reflect the need to include the `<queries>` tag in the Android manifest. Still working on moving the android-specific code into a dedicated android library, but this is a stopgap until that work wraps
