### ISSUE TITLE
JAR dependencies missing

### ISSUE THREAD

**Issue by stebond** [dropbox/dropbox-sdk-java#377]
Using NetBeans in a Desktop App and adding the dropbox-core-sdk-5.1.1.jar to the lib folder, is not possible to solve the followings imports:
import com.dropbox.core.DbxDownloader;
import com.dropbox.core.DbxException;
import com.dropbox.core.DbxRequestConfig;
import com.dropbox.core.v2.callbacks.DbxGlobalCallbackFactory;
import com.dropbox.core.v2.callbacks.DbxRouteErrorCallback;
import com.dropbox.core.v2.callbacks.DbxNetworkErrorCallback;
import com.dropbox.core.v2.DbxClientV2;
import com.dropbox.core.v2.files.FileMetadata;
import com.dropbox.core.v2.files.ListFolderResult;
import com.dropbox.core.v2.files.Metadata;
import com.dropbox.core.v2.users.FullAccount;

So it is not possible to include DropBox functionalities in my app.
Thank you for the response
Bets regards
Stefano

**Comment by greg-db** [comment]
Can you clarify what you mean when you say "is not possible to solve"? What error(s) do you get?

Also, since you've listed some specific classes, are you saying that only these classes in particular are not working, or that you are not able to import anything from the Dropbox library at all?

I also see you mentioned adding the jar to the lib folder. Can you confirm where/how you got the jar file, and how you've added the lib folder to your project?

In any case, we generally recommend using Gradle or Maven to manage your dependencies, as shown in the documentation: https://github.com/dropbox/dropbox-sdk-java#setup

**Comment by stebond** [comment]
1)I downloaded the jar file from https://github.com/dropbox/dropbox-sdk-java/releases/tag/v5.1.1
2) I added to the jar to the project;
3) when try to import some simple class they are missing from the jar file:
![SharedScreenshot](https://user-images.githubusercontent.com/38753854/150292004-f84b7269-325e-4f05-8751-0b2f60f43759.jpg)

**Comment by greg-db** [comment]
Can you share the actual error you're getting for reference?

Also, would you be able to use Gradle or Maven instead?

**Comment by stebond** [comment]
Dear Greg, 
I thik that the problem is related to the use of old jdk (I'm still using version 8) and the version of NetBeans used that is 8.1. I will try with a newer version and I will let you know. Thanks for the support

**Comment by handstandsam** [comment]
I'm going to close this due to inactivity.

NOTE: It is possible in the past that API spec definition changes could result in some classes not being there.  I ran into this with one of the typed exceptions that were being thrown, was no longer there.  In order to combat that, we'll be adding the https://github.com/Kotlin/binary-compatibility-validator to ensure we can surface any breaking changes to the API surface, even in the generated code from our API specs.
