### ISSUE TITLE
ProGuard rules for the dropbox libaray?

### ISSUE THREAD

**Issue by eicm** [dropbox/dropbox-sdk-java#41]
Hi what is the proguard rules to consider for the V2 library and also is it possible to replace OkHttp with any other library such as volley?

**Comment by cakoose** [comment]
I don't think we use any reflection, so you shouldn't need any special ProGuard rules.  Definitely let us know if you run into any issues.

The SDK's makes HTTP requests using the [HttpRequestor](https://github.com/dropbox/dropbox-sdk-java/blob/master/src/main/java/com/dropbox/core/http/HttpRequestor.java) interface.  There are currently two implementations of HttpRequestor: the default one uses HttpURLConnection and the alternate one uses OkHttp.  You can add more if you want.

I just read a little bit about Volley and at first glance, I don't think it can be used with this SDK.  It's an asynchronous library while this SDK is synchronous/blocking.  You'd have to create an asynchronous versions of each API call.  For example, Our C# SDK already provides both synchronous and asynchronous versions of each call, since this is common practice in C#.

**Comment by eicm** [comment]
@cakoose If I use the default one can I safely remove OkHttp from the dependencies?

**Comment by cakoose** [comment]
By "remove OkHttp from the dependencies", you mean from your own dependencies list, right?  In that case, yes, you can remove it.

Our SDK has "optional dependencies" on OkHttp, Android, and the Java Servlet API.  The core SDK doesn't depend on any of that stuff, but some of the helper classes do.  If you use the helper classes (like OkHttpRequestor), you also need the associated optional dependency in your project.  But if you don't, the JVM will never load the helper classes and thus will never look for the associated optional dependency.

**Comment by krieb** [comment]
@eicm The latest release has a section in the FAQ about ProGuard rules. Unfortunately the latest release currently uses Jackson Databind, so you will need to make sure you have rules that support that dependency. We hope to remove the dependency in future releases.

Note that older versions may not work well with ProGuard. I ran into some issues where ProGuard would overly optimize some constants that could result in `NullPointerException`s during some serializations.
