### ISSUE TITLE
expired_access_token

### ISSUE THREAD

**Issue by fadang123** [dropbox/dropbox-sdk-java#494]
expired_access_token,Generated access token生成得token只有4小时时效，怎么永远可以使用

**Comment by greg-db** [comment]
Dropbox is no longer offering the option for creating new long-lived access tokens. Dropbox is now issuing short-lived access tokens (and optional refresh tokens) instead of long-lived access tokens. You can find [more information on this migration here](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type).

Apps can still get long-term access by requesting "offline" access though, in which case the app receives a "refresh token" that can be used to retrieve new short-lived access tokens as needed, without further manual user intervention. You can find more information in the [OAuth Guide](https://developers.dropbox.com/oauth-guide) and [authorization documentation](https://www.dropbox.com/developers/documentation/http/documentation#authorization). There's a basic outline of processing this flow in [this blog post](https://dropbox.tech/developers/using-oauth-2-0-with-offline-access) which may serve as a useful example.
 
For examples of implementing this with [the Dropbox JavaScript SDK](https://github.com/dropbox/dropbox-sdk-js), please refer to the examples included in [the "examples" folder in the SDK](https://github.com/dropbox/dropbox-sdk-js/tree/main/examples/javascript). As long as you set the app key (a.k.a. client ID) and refresh token, like shown in [this example for the JavaScript SDK](https://github.com/dropbox/dropbox-sdk-js/blob/b5631e4b5b0e9eb6d3297e1ee57ad29a63d49898/examples/javascript/PKCE-backend/code_flow_example.js#L38), the SDK will actually handle refresh process for you automatically. The SDK will automatically catch expired access token errors and call the API to get a new short-lived access token when needed. Refresh tokens don't expire (though they can be revoked on demand), so if this is only for your own account, you would only need to get a refresh token for your own account once and could re-use that.

**Comment by greg-db** [comment]
Dropbox is no longer offering the option for creating new long-lived access tokens. Dropbox is now issuing short-lived access tokens (and optional refresh tokens) instead of long-lived access tokens. You can find [more information on this migration here](https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens#updating-access-token-type).

Apps can still get long-term access by requesting "offline" access though, in which case the app receives a "refresh token" that can be used to retrieve new short-lived access tokens as needed, without further manual user intervention. You can find more information in the [OAuth Guide](https://developers.dropbox.com/oauth-guide) and [authorization documentation](https://www.dropbox.com/developers/documentation/http/documentation#authorization). There's a basic outline of processing this flow in [this blog post](https://dropbox.tech/developers/using-oauth-2-0-with-offline-access) which may serve as a useful example.

The [official Dropbox Java SDK](https://github.com/dropbox/dropbox-sdk-java) can actually handle the process for you automatically, as long as you supply the necessary credentials, e.g., as shown retrieved in [the examples here](https://github.com/dropbox/dropbox-sdk-java/tree/main/examples/examples/src/main/java/com/dropbox/core/examples/authorize). For instance, for a client-side app, such as a desktop app, you should use the PKCE flow, e.g., [as shown here](https://github.com/dropbox/dropbox-sdk-java/blob/main/examples/examples/src/main/java/com/dropbox/core/examples/authorize/PkceAuthorize.java). That allows you to make and save [a DbxCredential with a refresh token as shown here](https://github.com/dropbox/dropbox-sdk-java/blob/main/examples/examples/src/main/java/com/dropbox/core/examples/authorize/AuthorizeExample.kt#L85). With that, you can make API calls [like shown here](https://github.com/dropbox/dropbox-sdk-java/blob/main/examples/examples/src/main/java/com/dropbox/core/examples/account_info/AccountInfoExample.kt#L26).
 
For Android apps using the [official Dropbox Java SDK](https://github.com/dropbox/dropbox-sdk-java), you should use the updated authorization functionality, starting with the startOAuth2PKCE method. You can find [an example app here](https://github.com/dropbox/dropbox-sdk-java/tree/main/examples/android). For instance, you can see [where that starts in the code here](https://github.com/dropbox/dropbox-sdk-java/blob/009c8eb3677f2a329bb43c7e2cb00df3f3d68aaf/examples/android/src/main/java/com/dropbox/core/examples/android/internal/api/DropboxOAuthUtil.kt#L52) and [how the result is handled here](https://github.com/dropbox/dropbox-sdk-java/blob/009c8eb3677f2a329bb43c7e2cb00df3f3d68aaf/examples/android/src/main/java/com/dropbox/core/examples/android/internal/api/DropboxOAuthUtil.kt#L83). When you use that functionality as shown, the SDK will then handle the refresh process for you automatically.
 
The refresh token doesn't expire automatically (though it can be revoked on demand), so it can be used repeatedly over a long period of time without manual user intervention.
