### ISSUE TITLE
Sign out

### ISSUE THREAD

**Issue by Samson721223** [dropbox/dropbox-sdk-java#54]
Hi all, could you tell how to sign out from my app on Android?

**Comment by pnikosis** [comment]
`dbxClientV2.auth().tokenRevoke()`

**Comment by Samson721223** [comment]
It is not working. It just unlink a existed account. I want users can log in another account.

**Comment by krieb** [comment]
@Samson721223 Once a user authorizes an app to access their account, that token is good until revoked. If you want to issue requests against the API as a different user, then you will need to get a new token for the new user. You can do this by going through the authorize flow again for the new user.

Note that we do not deal with usernames or passwords, just with authorization for an app to access a particular account. Your app can store and track the auth tokens as needed. As @pnikosis mentioned, you can revoke a token to guarantee the app can no longer access that account unless it is re-authorized.

The current SDK does not provide an Android Activity for this particular scenario. [AuthActivity.java](src/main/java/com/dropbox/core/android/AuthActivity.java) will perform authorization using the Dropbox app (if one exists on the phone), otherwise it will authorize through the web. This means you will always authorize as the user signed into the Dropbox app on the phone. If there is no Dropbox app, then you have a chance to switch users during the web authorization flow.

Can you describe your particular use case in more detail to see how we would update `AuthActivity.java` to handle this case?

**Comment by wangbourne** [comment]
@krieb 
I have revoked my token via: dbxClientV2.auth().tokenRevoke() and then executed Auth.startOAuth2Authentication again to launch a webview to log in.
The real problem is there's no username and password input on the webview. Instead, it's directly jumped to the "allow page", see attached.

![image](https://cloud.githubusercontent.com/assets/2090084/21463916/d11fd84a-c9bc-11e6-9be4-dbf3ece5eeff.png)

**Comment by Samson721223** [comment]
You need to clear the cache of webview.   http://stackoverflow.com/questions/2465432/android-webview-completely-clear-the-cache

**Comment by wangbourne** [comment]
@Samson721223 
you are right, thank

**Comment by fiasko131** [comment]
Hello,

Is there a way to switch from one account to another without revoking the accessToken. Since I migrated to V2 I can not manage several accounts with my app.
I always come back to the same account after:
`dropBoxService = null;`
`dropboxAccessToken = null;`
`Auth.startOAuth2Authentication(getActivity(), APP_KEY);`
And then in onResume() 
`dropboxAccessToken = Auth.getOAuth2Token();`




SolidExplorer for example switches from one account to another without losing the accessToken. I can not find the trick.

Thank you.``

**Comment by fiasko131** [comment]
This is because the client was not reinitialized in the DropBoxClientFactory.java provided in the android SDK example. Now everything is ok with:
`//make sDbxClient public in DropBoxFactory before 
DropboxClientFactory.sDbxClient = `null;`
