### ISSUE TITLE
BitmapFactory.decodeStream() returns null for getPreviewUrl()

### ISSUE THREAD

**Issue by phileo** [dropbox/dropbox-sdk-java#74]
I am requesting the sharing preview Url as follows:
`dbxClient.sharing().getFileMetadata(filePath).getPreviewUrl();`

The url I get back is:
`url = https://www.dropbox.com/scl/fi/f00yrcxcj4i9en80fl7ty`

I am trying to get the bitmap for this url as follows:
`bis = new BufferedInputStream(new URL(url).openConnection().getInputStream(), 8192)`

`bitmap = BitmapFactory.decodeStream(bis)`

Unfortunately, I am getting back a null bitmap.
Any ideas as to why this is happening, or what I am doing wrong?

Note: `new URL(url).openConnection().getResponseCode() < 300` for the above url

**Comment by greg-db** [comment]
Hi @phileo , the [getPreviewUrl method](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/sharing/SharedFileMetadata.html#getPreviewUrl--) returns a URL for a preview web page, not the file content itself:

> URL for displaying a web preview of the shared file.

That being the case, you can't get image data for it via `BitmapFactory` (since the URL is giving you HTML).

If you want the image data you can use [download](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#download-java.lang.String-) for the original data, or [getThumbnail](https://dropbox.github.io/dropbox-sdk-java/api-docs/v2.1.x/com/dropbox/core/v2/files/DbxUserFilesRequests.html#getThumbnail-java.lang.String-) for a thumbnail.
