### ISSUE TITLE
chunk upload file crash 

### ISSUE THREAD

**Issue by wangbourne** [dropbox/dropbox-sdk-java#88]
I reuse this part of code here: [https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java](url)

And found the remaining value could be negative from " long remaining = size - uploaded;", which could crash the app when executing "uploadAndFinish(in, remaining)"

By the way, I set the value of CHUNKED_UPLOAD_CHUNK_SIZE to be 1M and this crash happens when the uploaded file size is quite small (around 100k）

**Comment by cakoose** [comment]
If possible, can you provide the following:
- Your exact code.
- The version of the Dropbox SDK you're using.
- The output you saw when you ran your code.

On Dec 29, 2016 08:05, "Liang Wang" <notifications@github.com> wrote:

I reuse this part of code here: https://github.com/dropbox/
dropbox-sdk-java/blob/master/examples/upload-file/src/main/
java/com/dropbox/core/examples/upload_file/Main.java <http://url>

And found the remaining value could be negative from " long remaining =
size - uploaded;", which could crash the app when executing
"uploadAndFinish(in, remaining)"

by the way, i set the value of CHUNKED_UPLOAD_CHUNK_SIZE = 1M and this
crash happens when the uploaded file size is quite small (around 100k）

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/dropbox/dropbox-sdk-java/issues/88>, or mute the thread

**Comment by wangbourne** [comment]
1. SDK: com.dropbox.core:dropbox-core-sdk:2.1.2
2. Code:I exactly use the code from: [https://github.com/dropbox/
dropbox-sdk-java/blob/master/examples/upload-file/src/main/
java/com/dropbox/core/examples/upload_file/Main.java](url) except I change CHUNKED_UPLOAD_CHUNK_SIZE = 1024*1024
3. Screenshot:
![image](https://cloud.githubusercontent.com/assets/2090084/21556532/00fec90e-ce6d-11e6-9dfd-0d6376f4786d.png)

**Comment by greg-db** [comment]
If your file is around 100K, you shouldn't be using that code path anyway. For small files, you can just use the simpler single upload call.

The example code as provided handles this for you here, by choosing which kind of upload to use, depending on the local file size:

https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/upload-file/src/main/java/com/dropbox/core/examples/upload_file/Main.java#L270

You should probably do the same in your app.

**Comment by wangbourne** [comment]
In the sample code, you recommend CHUNKED_UPLOAD_CHUNK_SIZE to be 4M. It may not be a good number if internet speed is quite slow.
my question then is: what's the suggested file size that  determine to use  chunkedUploadFile or uploadFile while avoiding crash could be guranteed.

**Comment by greg-db** [comment]
There isn't really a single answer to this unfortunately, as it depends on the specifics of the situation. 

For what its worth, you can technically use upload sessions to upload smaller files, but the example just isn't written for that.

**Comment by wangbourne** [comment]
Your explanation makes somewhat sense. However,  crash should be avoided in any case, don't you think so?

I have benign using Dropbox SDK for more than 3 years and I do like the old APIs with capabilities of:
1. progressive uploading with a beautiful callback
2. one api to upload a file without any confusion.

**Comment by nzala** [comment]
+1
